using Verse;

namespace BiomesCore.ModSettings
{
	/// <summary>
	/// Contains data for all settings values. The default values of this object are the initial default settings for the mod.
	/// </summary>
	public class SettingValues
	{
		/// <summary>
		/// Some of the plants in Biomes! have a custom growing hours interval. Mods that modify the growing hours of
		/// regular plants might fail to work with these plants.  If this setting is set to true, Biomes! plants with custom
		/// growing hours will grow for the entire day period instead.
		/// </summary>
		public bool SetCustomGrowingHoursToAll = false;

		/// <summary>
		/// Scale the amount of power generated by the powergen fungus. This setting is modified in Biomes! Caverns, but
		/// since CompPowerPlant_PowerFungus is in Core, the setting is saved here instead. This will also keep config
		/// compatibility if at some point we decide to move the powergen fungus or implement a similar building.
		/// </summary>
		public int PowerGenFungusMultiplier = 100;
	}

	/// <summary>
	/// Allows the rest of the mod to access a SettingValues instance. Handles resetting, save and load.
	/// </summary>
	public class Settings : Verse.ModSettings
	{
		/// <summary>
		/// Single instance of the setting values of this mod. Uses static for performance reasons.
		/// </summary>
		public static SettingValues Values = new SettingValues();

		/// <summary>
		/// Set all settings to their default values.
		/// </summary>
		public static void Reset()
		{
			Values = new SettingValues();
		}

		/// <summary>
		/// Save and load preferences.
		/// </summary>
		public override void ExposeData()
		{
			base.ExposeData();
			Scribe_Values.Look(ref Values.SetCustomGrowingHoursToAll, nameof(Values.SetCustomGrowingHoursToAll),
				defaultValue: false);

			Scribe_Values.Look(ref Values.PowerGenFungusMultiplier, nameof(Values.PowerGenFungusMultiplier),
				defaultValue: 100);
		}
	}
}